ASLDRO-51: Changed test nibabel tempfile scope
Changed the scope of the TemporaryDirectory in nibabel tests in
order to fix the issue with Windows throwing a:
PermissionError: [WinError 32] The process cannot access the file
because it is being used